### ISSUE TITLE
understanding parent db vs admin db

### ISSUE THREAD

**Issue by MalikAbdCom** [notrab/turso-per-user-starter#7]
i am trying to understand how db per user is going to be used, by creating parent db to be cloned by child db, it means if i want to separate admin only data there will be another database for just admin only if needed right?
for example, as an super admin who owns the website, i want to collect data for subscription invoices, list of stores, chat between super admin and each store created (which will be 1 db per store as my understanding), i will be create 3 databases at first, super admin db, parent db to be cloned by child db, and the child db it self.
please correct me if i am wrong at this.

**Comment by notrab** [comment]
Hey @MalikAbdCom 

This repo currently showcases creating a database per-user, where each database is isolated, but shares a single schema.

This means that;

1. No data is shared
2. If you need a new table/field, you add it to the parent, and every child db is updated to include that
3. Data added to the parent db (not recommended) is added to all child dbs

I typically reach for **Multi-DB Schemas Per-User** when:

1. You need strong data isolation between users for security or compliance.
2. There is no overlap of data between any of the databases.

If you're looking to build something on a **Per-Tenant** basis, I would change this demo so that:

1. Databases are created for new organizations/teams.
2. Data is shared across users in the same team
3. Data isolation per user isn't a requirement, but per-tenant is

This demo builds on the Turso Multi-DB Schemas feature, which doesn't fit all use cases. For example, if you need to aggregate data or perform queries across all databases, this gets more tricky. You either have to:

1. Use `ATTACH` which is limited to only a small number of databases you can query across
2. Use a separate "meta" database to store anything you later need to aggregate

You might find if you need to query across all databases that you use a single database and separate tenants/users on a table basis.

---

For your use case, you might not benefit from multi-db schemas, unless you opt to manage subscriptions in a single "meta" database. If you look at the code I'm doing here with Clerk for auth, I'm essentially doing that... but just using Clerk to manage my hypothetical users table.

**Comment by MalikAbdCom** [comment]
i think what i am  looking for is per-tenant basis base on your explanation, i might to reconsider how i designing my database base on my use case, thank you @notrab.
